In [1]:
Dataset:2005-2017
Number of Datapoints:1048575
Output feature: first_degree_hx

In [34]:
#importing the libraries
import pandas as pd
import matplotlib as plt
import numpy as np
import random
import warnings

In [4]:
import os
import glob
import pandas as pd
os.chdir(r"C:\Users\krish\anaconda3\csv")

In [8]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [9]:
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_csv.csv", index=False, encoding='utf-8-sig')

In [35]:
#importing the dataset
data = pd.read_csv(r'C:\Users\krish\anaconda3\csv\combined_csv.csv')
#data.head()
print(data)
X = data.iloc[:, [0,11]]
Y = data.iloc[:, 12]

         year  race_eth  age_menarche  age_first_birth  current_hrt  menopaus  \
0        2005         1             0                0            0         1   
1        2005         1             0                0            0         1   
2        2005         1             0                0            0         1   
3        2005         1             0                0            0         1   
4        2005         1             0                1            0         1   
...       ...       ...           ...              ...          ...       ...   
1048570  2013         2             1                3            0         2   
1048571  2013         2             1                3            0         2   
1048572  2013         2             1                3            0         2   
1048573  2013         2             1                3            0         2   
1048574  2013         2             1                3            0         2   

         bmi_group  biophx 

In [36]:
#find missing values,if any
data.isnull()

year  race_eth  age_menarche  age_first_birth  current_hrt  \
0        False     False         False            False        False   
1        False     False         False            False        False   
2        False     False         False            False        False   
3        False     False         False            False        False   
4        False     False         False            False        False   
...        ...       ...           ...              ...          ...   
1048570  False     False         False            False        False   
1048571  False     False         False            False        False   
1048572  False     False         False            False        False   
1048573  False     False         False            False        False   
1048574  False     False         False            False        False   

         menopaus  bmi_group  biophx  count  BIRADS_breast_density  \
0           False      False   False  False                  False   
1           False      False   False  False                  False   
2           False      False   False  False                  False   
3           False      False   False  False                  False   
4           False      False   False  False                  False   
...           ...        ...     ...    ...                    ...   
1048570     False      False   False  False                  False   
1048571     False      False   False  False                  False   
1048572     False      False   False  False                  False   
1048573     False      False   False  False                  False   
1048574     False      False   False  False                  False   

         breast_cancer_history    age  first_degree_hx  
0                        False  False            False  
1                        False  False            False  
2                        False  False            False  
3                        False  False            False  
4                        False  False            False  
...                        ...    ...              ...  
1048570                  False  False            False  
1048571                  False  False            False  
1048572                  False  False            False  
1048573                  False  False            False  
1048574                  False  False            False  

[1048575 rows x 13 columns]

In [4]:
#Missing Data Percentage List
for col in data.columns:
    pct_missing = np.mean(data[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))

year - 0%
race_eth - 0%
first_degree_hx - 0%
age_menarche - 0%
age_first_birth - 0%
BIRADS_breast_density - 0%
current_hrt - 0%
menopaus - 0%
bmi_group - 0%
biophx - 0%
count - 0%
breast_cancer_history - 0%
age - 0%


In [4]:
#removing duplicate rows
data1 = data.drop_duplicates()
print(data1.shape)

(1048575, 13)


In [5]:
print(data)

         year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
0        2005         1                0             0                0   
1        2005         1                0             0                0   
2        2005         1                0             0                0   
3        2005         1                0             0                0   
4        2005         1                0             0                1   
...       ...       ...              ...           ...              ...   
1048570  2013         2                0             1                3   
1048571  2013         2                0             1                3   
1048572  2013         2                0             1                3   
1048573  2013         2                0             1                3   
1048574  2013         2                0             1                3   

         current_hrt  menopaus  bmi_group  biophx  count  \
0                  0         1         

In [6]:
data.dtypes

year                     int64
race_eth                 int64
first_degree_hx          int64
age_menarche             int64
age_first_birth          int64
current_hrt              int64
menopaus                 int64
bmi_group                int64
biophx                   int64
count                    int64
BIRADS_breast_density    int64
age                      int64
breast_cancer_history    int64
dtype: object

In [5]:
#pre processing the data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(-1, 1)).fit(X)
X = scaler.fit_transform(X)

In [6]:
#shuffling the data
data = data.sample(frac=1).reset_index(drop=True)

In [7]:
data.head()

year  race_eth  age_menarche  age_first_birth  current_hrt  menopaus  \
0  2012         2             1                4            0         1   
1  2009         1             9                4            0         2   
2  2007         1             9                3            9         9   
3  2006         1             0                1            9         2   
4  2007         5             9                3            9         1   

   bmi_group  biophx  count  BIRADS_breast_density  age  \
0          2       0     14                      3    6   
1          3       0      3                      3    6   
2          1       0      1                      3    6   
3          3       0      1                      2    8   
4          1       0      1                      2    5   

   breast_cancer_history  first_degree_hx  
0                      0                0  
1                      0                9  
2                      9                1  
3                      9                9  
4                      0                0

In [37]:
#Splitting the dataset into the Training set and Test set to 80 and 20
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 123)
print (X_train.shape , Y_train.shape)
print (X_test.shape, Y_test.shape)

(838860, 2) (838860,)
(209715, 2) (209715,)


In [38]:
data.tail()

year  race_eth  age_menarche  age_first_birth  current_hrt  menopaus  \
1048570  2013         2             1                3            0         2   
1048571  2013         2             1                3            0         2   
1048572  2013         2             1                3            0         2   
1048573  2013         2             1                3            0         2   
1048574  2013         2             1                3            0         2   

         bmi_group  biophx  count  BIRADS_breast_density  \
1048570          4       1      1                      1   
1048571          1       0      6                      2   
1048572          1       1      4                      2   
1048573          2       0      8                      2   
1048574          2       1      3                      2   

         breast_cancer_history  age  first_degree_hx  
1048570                      1    9                0  
1048571                      0    9                0  
1048572                      0    9                0  
1048573                      0    9                0  
1048574                      0    9                0

In [39]:
#ignore all caught warnings   
with warnings.catch_warnings():
    warnings.filterwarnings("ignore")

from sklearn.model_selection import KFold
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score
cv = KFold(n_splits=10, random_state=42, shuffle=True)
print ("Train Set                                            Test Set         ")
for train_set,test_set in cv.split(X):
    print(train_set , test_set)

Train Set                                            Test Set         
[      1       2       3 ... 1048572 1048573 1048574] [      0      12      14 ... 1048554 1048557 1048564]
[      0       1       2 ... 1048571 1048573 1048574] [      7      20      36 ... 1048560 1048567 1048572]
[      0       1       2 ... 1048572 1048573 1048574] [     10      17      24 ... 1048513 1048543 1048566]
[      0       1       2 ... 1048572 1048573 1048574] [      6       9      32 ... 1048540 1048558 1048563]
[      0       1       3 ... 1048570 1048571 1048572] [      2      11      29 ... 1048561 1048573 1048574]
[      0       1       2 ... 1048572 1048573 1048574] [     26      30      40 ... 1048522 1048542 1048570]
[      0       1       2 ... 1048572 1048573 1048574] [      4      16      19 ... 1048523 1048526 1048527]
[      0       2       3 ... 1048572 1048573 1048574] [      1      46      66 ... 1048552 1048562 1048565]
[      0       1       2 ... 1048572 1048573 1048574] [      3   

In [11]:
#Randomforest classification
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 100, random_state = 1) # Instantiate model with 100 decision trees
rf.fit(X_train, Y_train);#train model on training data

In [12]:
predictions = rf.predict(X_test) #make predictions on test data
errors = abs(predictions - Y_test) #calculate absolute errors
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.83 degrees.


In [13]:
#calculating accuracy
mape = 100 * (errors / Y_test) #calculate mean absolute percentage error mape
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 0.0 %.


In [14]:
#Naive Bayes calssification
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
model = GaussianNB()
model.fit(X_train,Y_train)

GaussianNB()

In [15]:
Y_pred = model.predict(X_test)

In [16]:
accuracy = accuracy_score(Y_test,Y_pred)*100
accuracy

67.3404382137663

In [42]:
from sklearn import svm

In [43]:
clf = svm.SVC(kernel='linear')

In [ ]:
clf.fit(X_train,Y_train)

In [ ]:
Y_pred = clf.predict(X_test)

In [ ]:
from sklearn import metrics

In [ ]:
print("accuracy:", metrics.accuracy_score(Y_test,Y_pred))

In [26]:
from sklearn.metrics import confusion_matrix
from sklearn import tree, metrics
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [27]:
dtree = tree.DecisionTreeClassifier(criterion='entropy', max_depth=5,random_state=0)
dtree.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=0)

In [28]:
y_pred = dtree.predict(X_test)

In [29]:
count_misclassified = (Y_test != y_pred).sum()
print('Misclassified samples: {}'.format(count_misclassified))
accuracy = metrics.accuracy_score(Y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))

Misclassified samples: 40546
Accuracy: 0.60


In [40]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import matplotlib as plt
import numpy as np
import random
import warnings

In [41]:
#importing the dataset
data = pd.read_csv(r'C:\Users\krish\anaconda3\csv\combined_csv.csv')
#data.head()
print(data)
X = data.iloc[:, [0,11]]
Y = data.iloc[:, 12]

         year  race_eth  age_menarche  age_first_birth  current_hrt  menopaus  \
0        2005         1             0                0            0         1   
1        2005         1             0                0            0         1   
2        2005         1             0                0            0         1   
3        2005         1             0                0            0         1   
4        2005         1             0                1            0         1   
...       ...       ...           ...              ...          ...       ...   
1048570  2013         2             1                3            0         2   
1048571  2013         2             1                3            0         2   
1048572  2013         2             1                3            0         2   
1048573  2013         2             1                3            0         2   
1048574  2013         2             1                3            0         2   

         bmi_group  biophx 

In [42]:
# define the keras model
model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [43]:
#compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [46]:
# fit the keras model on the dataset
model.fit(X, Y, epochs=5, batch_size=10)

Epoch 1/5
1048575/1048575 [==============================] - 198s 189us/step - loss: 0.4493 - accuracy: 0.2649
Epoch 2/5
1048575/1048575 [==============================] - 195s 186us/step - loss: 0.4494 - accuracy: 0.2649
Epoch 3/5
1048575/1048575 [==============================] - 195s 186us/step - loss: 0.4494 - accuracy: 0.2649
Epoch 4/5
1048575/1048575 [==============================] - 197s 188us/step - loss: 0.4494 - accuracy: 0.2649
Epoch 5/5
1048575/1048575 [==============================] - 209s 199us/step - loss: 0.4495 - accuracy: 0.2649


In [47]:
# evaluate the keras model
_, accuracy = model.evaluate(X, Y)
print('Accuracy: %.2f' % (accuracy*100))

1048575/1048575 [==============================] - 22s 21us/step
Accuracy: 26.49
