In [1]:
Dataset:2013-2017
Number of Datapoints:506467
Output feature: age

In [1]:
#importing the libraries
import pandas as pd
import matplotlib as plt
import numpy as np
import random
import warnings

In [4]:
import os
import glob
import pandas as pd
os.chdir(r"C:\Users\krish\anaconda3\csv")

In [8]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [9]:
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_csv.csv", index=False, encoding='utf-8-sig')

In [2]:
#importing the dataset
data = pd.read_csv(r'C:\Users\krish\anaconda3\csv\bcsc2013.csv')
#data.head()
print(data)
X = data.iloc[:, [0,10]]
Y = data.iloc[:, 11]

        year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
0       2013         1                0             9                9   
1       2013         1                0             9                9   
2       2013         1                0             9                9   
3       2013         1                0             9                9   
4       2013         1                0             9                9   
...      ...       ...              ...           ...              ...   
506461  2017         9                9             9                9   
506462  2017         9                9             9                9   
506463  2017         9                9             9                9   
506464  2017         9                9             9                9   
506465  2017         9                9             9                9   

        BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
0                           9       

In [3]:
#find missing values,if any
data.isnull()

year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
0       False     False            False         False            False   
1       False     False            False         False            False   
2       False     False            False         False            False   
3       False     False            False         False            False   
4       False     False            False         False            False   
...       ...       ...              ...           ...              ...   
506461  False     False            False         False            False   
506462  False     False            False         False            False   
506463  False     False            False         False            False   
506464  False     False            False         False            False   
506465  False     False            False         False            False   

        BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
0                       False        False     False      False   False   
1                       False        False     False      False   False   
2                       False        False     False      False   False   
3                       False        False     False      False   False   
4                       False        False     False      False   False   
...                       ...          ...       ...        ...     ...   
506461                  False        False     False      False   False   
506462                  False        False     False      False   False   
506463                  False        False     False      False   False   
506464                  False        False     False      False   False   
506465                  False        False     False      False   False   

        breast_cancer_history    age  
0                       False  False  
1                       False  False  
2                       False  False  
3                       False  False  
4                       False  False  
...                       ...    ...  
506461                  False  False  
506462                  False  False  
506463                  False  False  
506464                  False  False  
506465                  False  False  

[506466 rows x 12 columns]

In [5]:
#Missing Data Percentage List
for col in data.columns:
    pct_missing = np.mean(data[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))

year - 0%
race_eth - 0%
first_degree_hx - 0%
age_menarche - 0%
age_first_birth - 0%
BIRADS_breast_density - 0%
current_hrt - 0%
menopaus - 0%
bmi_group - 0%
biophx - 0%
count - 0%
breast_cancer_history - 0%
age - 0%


In [6]:
#removing duplicate rows
data1 = data.drop_duplicates()
print(data1.shape)

(506466, 13)


In [7]:
print(data)

        year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
0       2013         1                0             9                9   
1       2013         1                0             9                9   
2       2013         1                0             9                9   
3       2013         1                0             9                9   
4       2013         1                0             9                9   
...      ...       ...              ...           ...              ...   
506461  2017         9                9             9                9   
506462  2017         9                9             9                9   
506463  2017         9                9             9                9   
506464  2017         9                9             9                9   
506465  2017         9                9             9                9   

        BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
0                           9       

In [8]:
data.dtypes

year                     int64
race_eth                 int64
first_degree_hx          int64
age_menarche             int64
age_first_birth          int64
BIRADS_breast_density    int64
current_hrt              int64
menopaus                 int64
bmi_group                int64
biophx                   int64
count                    int64
breast_cancer_history    int64
age                      int64
dtype: object

In [4]:
data.age.unique()

array([ 7,  8,  9, 10, 11, 12, 13,  1,  2,  3,  4,  5,  6], dtype=int64)

In [5]:
data.age.value_counts()

7     89019
6     70841
8     62206
9     59652
5     49942
10    48966
11    34689
4     34495
12    22795
13    14557
3     12084
2      5793
1      1427
Name: age, dtype: int64

In [6]:
label_numbers = ['group1', 'group2', 'group3']
cut_bins = [0, 4, 8, 13]
age_groups = pd.cut(data['age'], bins=cut_bins, labels=label_numbers)
age_groups

0         group2
1         group2
2         group2
3         group2
4         group2
           ...  
506461    group3
506462    group3
506463    group3
506464    group3
506465    group3
Name: age, Length: 506466, dtype: category
Categories (3, object): ['group1' < 'group2' < 'group3']

In [7]:
age_groups.value_counts()
#pd.cut(data['age_groups'],bins=3).value_counts()

group2    272008
group3    180659
group1     53799
Name: age, dtype: int64

In [8]:
df = pd.DataFrame(data)
df['age_subgroups'] = age_groups
df

year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
0       2013         1                0             9                9   
1       2013         1                0             9                9   
2       2013         1                0             9                9   
3       2013         1                0             9                9   
4       2013         1                0             9                9   
...      ...       ...              ...           ...              ...   
506461  2017         9                9             9                9   
506462  2017         9                9             9                9   
506463  2017         9                9             9                9   
506464  2017         9                9             9                9   
506465  2017         9                9             9                9   

        BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
0                           9            0         2          2       1   
1                           9            0         2          2       1   
2                           9            0         2          3       0   
3                           9            0         2          3       0   
4                           9            0         2          3       1   
...                       ...          ...       ...        ...     ...   
506461                      1            9         2          9       1   
506462                      2            0         2          9       0   
506463                      2            9         2          9       9   
506464                      3            0         2          9       0   
506465                      3            9         2          9       9   

        breast_cancer_history  age age_subgroups  
0                           0    7        group2  
1                           1    7        group2  
2                           0    7        group2  
3                           9    7        group2  
4                           0    7        group2  
...                       ...  ...           ...  
506461                      0   13        group3  
506462                      0   13        group3  
506463                      9   13        group3  
506464                      0   13        group3  
506465                      0   13        group3  

[506466 rows x 13 columns]

In [14]:
#ownloading the updated csv file to local desktop
df.to_csv(r"C:\Users\krish\anaconda3\csv\updated2013.csv")

In [3]:
#pre processing the data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(-1, 1)).fit(X)
X = scaler.fit_transform(X)

In [4]:
#shuffling the data
data = data.sample(frac=1).reset_index(drop=True)

In [11]:
data.head()

year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
0  2016         1                0             2                1   
1  2016         3                0             9                9   
2  2015         1                0             9                9   
3  2014         6                0             9                3   
4  2014         6                1             9                3   

   BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
0                      2            9         3          4       0   
1                      2            0         1          3       9   
2                      1            0         9          4       0   
3                      2            0         2          4       0   
4                      3            0         2          1       0   

   breast_cancer_history  age age_subgroups  
0                      9    7        group2  
1                      0    7        group2  
2                      0    5        group2  
3                      0    8        group2  
4                      0    6        group2

In [5]:
#Splitting the dataset into the Training set and Test set to 80 and 20
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 123)
print (X_train.shape , Y_train.shape)
print (X_test.shape, Y_test.shape)

(405172, 2) (405172,)
(101294, 2) (101294,)


In [13]:
data.tail()

year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
506461  2016         1                0             9                9   
506462  2013         1                1             1                3   
506463  2017         1                0             2                9   
506464  2014         1                0             0                2   
506465  2015         1                0             9                4   

        BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
506461                      3            9         2          4       9   
506462                      3            9         2          2       9   
506463                      4            0         2          9       1   
506464                      9            9         2          9       9   
506465                      3            0         2          1       0   

        breast_cancer_history  age age_subgroups  
506461                      9    8        group2  
506462                      9   13        group3  
506463                      0    8        group2  
506464                      9   10        group3  
506465                      0    4        group1

In [14]:
#ignore all caught warnings   
with warnings.catch_warnings():
    warnings.filterwarnings("ignore")

from sklearn.model_selection import KFold
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score
cv = KFold(n_splits=10, random_state=42, shuffle=True)
print ("Train Set                                            Test Set         ")
for train_set,test_set in cv.split(X):
    print(train_set , test_set)

Train Set                                            Test Set         
[     0      1      2 ... 506462 506464 506465] [     6      7     24 ... 506449 506461 506463]
[     0      1      3 ... 506462 506463 506464] [     2     26     39 ... 506442 506448 506465]
[     0      1      2 ... 506463 506464 506465] [    11     28     35 ... 506395 506446 506455]
[     1      2      3 ... 506462 506463 506465] [     0     16     17 ... 506452 506454 506464]
[     0      1      2 ... 506463 506464 506465] [    10     12     20 ... 506420 506433 506457]
[     0      1      2 ... 506463 506464 506465] [     4     29     38 ... 506447 506456 506462]
[     0      2      3 ... 506463 506464 506465] [     1      8      9 ... 506429 506445 506451]
[     0      1      2 ... 506463 506464 506465] [     3     14     23 ... 506443 506450 506459]
[     0      1      2 ... 506463 506464 506465] [    13     19     25 ... 506392 506402 506421]
[     0      1      2 ... 506463 506464 506465] [     5     15   

In [15]:
#Randomforest classification
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 100, random_state = 1) # Instantiate model with 100 decision trees
rf.fit(X_train, Y_train);#train model on training data

In [16]:
predictions = rf.predict(X_test) #make predictions on test data
errors = abs(predictions - Y_test) #calculate absolute errors
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 2.02 degrees.


In [17]:
#calculating accuracy
mape = 100 * (errors / Y_test) #calculate mean absolute percentage error mape
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 69.62 %.


In [18]:
#Naive Bayes calssification
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
model = GaussianNB()
model.fit(X_train,Y_train)

GaussianNB()

In [19]:
Y_pred = model.predict(X_test)

In [20]:
accuracy = accuracy_score(Y_test,Y_pred)*100
accuracy

17.51831302939957

In [42]:
from sklearn import svm

In [43]:
clf = svm.SVC(kernel='linear')

In [ ]:
clf.fit(X_train,Y_train)

In [ ]:
Y_pred = clf.predict(X_test)

In [ ]:
from sklearn import metrics

In [ ]:
print("accuracy:", metrics.accuracy_score(Y_test,Y_pred))

In [47]:
from sklearn.metrics import confusion_matrix
from sklearn import tree, metrics
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [48]:
dtree = tree.DecisionTreeClassifier(criterion='entropy', max_depth=5,random_state=0)
dtree.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=0)

In [49]:
y_pred = dtree.predict(X_test)

In [50]:
count_misclassified = (Y_test != y_pred).sum()
print('Misclassified samples: {}'.format(count_misclassified))
accuracy = metrics.accuracy_score(Y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))

Misclassified samples: 83166
Accuracy: 0.18


In [6]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import matplotlib as plt
import numpy as np
import random
import warnings

Using TensorFlow backend.


In [7]:
#importing the dataset
data = pd.read_csv(r'C:\Users\krish\anaconda3\csv\bcsc2013.csv')
#data.head()
print(data)
X = data.iloc[:, [0,10]]
Y = data.iloc[:, 11]

        year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
0       2013         1                0             9                9   
1       2013         1                0             9                9   
2       2013         1                0             9                9   
3       2013         1                0             9                9   
4       2013         1                0             9                9   
...      ...       ...              ...           ...              ...   
506461  2017         9                9             9                9   
506462  2017         9                9             9                9   
506463  2017         9                9             9                9   
506464  2017         9                9             9                9   
506465  2017         9                9             9                9   

        BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
0                           9       

In [8]:
# define the keras model
model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [9]:
#compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# fit the keras model on the dataset
model.fit(X, Y, epochs=150, batch_size=32)

Epoch 1/150
506466/506466 [==============================] - 29s 57us/step - loss: -233482190.0683 - accuracy: 0.1519
Epoch 2/150
506466/506466 [==============================] - 25s 50us/step - loss: -2489549296.6238 - accuracy: 0.1519
Epoch 3/150
506466/506466 [==============================] - 23s 46us/step - loss: -9206574510.4566 - accuracy: 0.1519
Epoch 4/150
506466/506466 [==============================] - 27s 53us/step - loss: -22676432747.3493 - accuracy: 0.1519
Epoch 5/150
506466/506466 [==============================] - 27s 54us/step - loss: -45176520023.7838 - accuracy: 0.1519
Epoch 6/150
506466/506466 [==============================] - 29s 58us/step - loss: -78872989339.9435 - accuracy: 0.1519
Epoch 7/150
506466/506466 [==============================] - 25s 50us/step - loss: -125927716984.2518 - accuracy: 0.1519
Epoch 8/150
506466/506466 [==============================] - 22s 44us/step - loss: -188913992694.2264 - accuracy: 0.1519
Epoch 9/150
506466/506466 [===============

In [26]:
# evaluate the keras model
_, accuracy = model.evaluate(X, Y)
print('Accuracy: %.2f' % (accuracy*100))

506466/506466 [==============================] - 11s 22us/step
Accuracy: 0.28
