In [1]:
Dataset:2013-2017
Number of Datapoints:506467
Output feature: breast_cancer_history

In [3]:
#importing the libraries
import pandas as pd
import matplotlib as plt
import numpy as np
import random
import warnings

In [4]:
import os
import glob
import pandas as pd
os.chdir(r"C:\Users\krish\anaconda3\csv")

In [8]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [9]:
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_csv.csv", index=False, encoding='utf-8-sig')

In [4]:
#importing the dataset
data = pd.read_csv(r'C:\Users\krish\anaconda3\csv\bcsc2013.csv')
#data.head()
print(data)
X = data.iloc[:, [0,10]]
Y = data.iloc[:, 11]

        year  race_eth  age_menarche  age_first_birth  current_hrt  menopaus  \
0       2013         1             9                9            0         2   
1       2013         1             9                9            0         2   
2       2013         1             9                9            0         2   
3       2013         1             9                9            0         2   
4       2013         1             9                9            0         2   
...      ...       ...           ...              ...          ...       ...   
506461  2017         9             9                9            9         2   
506462  2017         9             9                9            0         2   
506463  2017         9             9                9            9         2   
506464  2017         9             9                9            0         2   
506465  2017         9             9                9            9         2   

        bmi_group  biophx  count  age  

In [45]:
#find missing values,if any
data.isnull()

year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
0       False     False            False         False            False   
1       False     False            False         False            False   
2       False     False            False         False            False   
3       False     False            False         False            False   
4       False     False            False         False            False   
...       ...       ...              ...           ...              ...   
506461  False     False            False         False            False   
506462  False     False            False         False            False   
506463  False     False            False         False            False   
506464  False     False            False         False            False   
506465  False     False            False         False            False   

        BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
0                       False        False     False      False   False   
1                       False        False     False      False   False   
2                       False        False     False      False   False   
3                       False        False     False      False   False   
4                       False        False     False      False   False   
...                       ...          ...       ...        ...     ...   
506461                  False        False     False      False   False   
506462                  False        False     False      False   False   
506463                  False        False     False      False   False   
506464                  False        False     False      False   False   
506465                  False        False     False      False   False   

          age  breast_cancer_history  
0       False                  False  
1       False                  False  
2       False                  False  
3       False                  False  
4       False                  False  
...       ...                    ...  
506461  False                  False  
506462  False                  False  
506463  False                  False  
506464  False                  False  
506465  False                  False  

[506466 rows x 12 columns]

In [4]:
#Missing Data Percentage List
for col in data.columns:
    pct_missing = np.mean(data[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))

year - 0%
race_eth - 0%
first_degree_hx - 0%
age_menarche - 0%
age_first_birth - 0%
BIRADS_breast_density - 0%
current_hrt - 0%
menopaus - 0%
bmi_group - 0%
biophx - 0%
count - 0%
breast_cancer_history - 0%
age - 0%


In [12]:
#removing duplicate rows
data1 = data.drop_duplicates()
print(data1.shape)

(506466, 13)


In [13]:
print(data)

        year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
0       2013         1                0             9                9   
1       2013         1                0             9                9   
2       2013         1                0             9                9   
3       2013         1                0             9                9   
4       2013         1                0             9                9   
...      ...       ...              ...           ...              ...   
506461  2017         9                9             9                9   
506462  2017         9                9             9                9   
506463  2017         9                9             9                9   
506464  2017         9                9             9                9   
506465  2017         9                9             9                9   

        BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
0                           9       

In [8]:
data.dtypes

year                     int64
race_eth                 int64
first_degree_hx          int64
age_menarche             int64
age_first_birth          int64
BIRADS_breast_density    int64
current_hrt              int64
menopaus                 int64
bmi_group                int64
biophx                   int64
count                    int64
breast_cancer_history    int64
age                      int64
dtype: object

In [4]:
#pre processing the data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(-1, 1)).fit(X)
X = scaler.fit_transform(X)

In [5]:
#shuffling the data
data = data.sample(frac=1).reset_index(drop=True)

In [6]:
data.head()

year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
0  2016.0         1              1.0           0.0              9.0   
1  2017.0         2              1.0           1.0              1.0   
2  2017.0         1              1.0           1.0              1.0   
3  2015.0         2              0.0           0.0              2.0   
4  2014.0         1              1.0           9.0              9.0   

   BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  count  \
0                    2.0          0.0       2.0        9.0     1.0    1.0   
1                    4.0          0.0       3.0        1.0     0.0    1.0   
2                    2.0          9.0       2.0        3.0     0.0    1.0   
3                    2.0          9.0       2.0        3.0     0.0    1.0   
4                    2.0          9.0       2.0        2.0     9.0    1.0   

    age  breast_cancer_history  
0  10.0                    1.0  
1   4.0                    0.0  
2   9.0                    9.0  
3   7.0                    9.0  
4   6.0                    9.0

In [5]:
#Splitting the dataset into the Training set and Test set to 80 and 20
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 123)
print (X_train.shape , Y_train.shape)
print (X_test.shape, Y_test.shape)

(405172, 2) (405172,)
(101294, 2) (101294,)


In [6]:
data.tail()

year  race_eth  age_menarche  age_first_birth  current_hrt  menopaus  \
506461  2017         9             9                9            9         2   
506462  2017         9             9                9            0         2   
506463  2017         9             9                9            9         2   
506464  2017         9             9                9            0         2   
506465  2017         9             9                9            9         2   

        bmi_group  biophx  count  age  BIRADS_breast_density  \
506461          9       1      1   13                      1   
506462          9       0      1   13                      2   
506463          9       9      1   13                      2   
506464          9       0      1   13                      3   
506465          9       9      1   13                      3   

        breast_cancer_history  first_degree_hx  
506461                      0                9  
506462                      0                9  
506463                      9                9  
506464                      0                9  
506465                      0                9

In [7]:
#ignore all caught warnings   
with warnings.catch_warnings():
    warnings.filterwarnings("ignore")

from sklearn.model_selection import KFold
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score
cv = KFold(n_splits=10, random_state=42, shuffle=True)
print ("Train Set                                            Test Set         ")
for train_set,test_set in cv.split(X):
    print(train_set , test_set)

Train Set                                            Test Set         
[     0      1      2 ... 506462 506464 506465] [     6      7     24 ... 506449 506461 506463]
[     0      1      3 ... 506462 506463 506464] [     2     26     39 ... 506442 506448 506465]
[     0      1      2 ... 506463 506464 506465] [    11     28     35 ... 506395 506446 506455]
[     1      2      3 ... 506462 506463 506465] [     0     16     17 ... 506452 506454 506464]
[     0      1      2 ... 506463 506464 506465] [    10     12     20 ... 506420 506433 506457]
[     0      1      2 ... 506463 506464 506465] [     4     29     38 ... 506447 506456 506462]
[     0      2      3 ... 506463 506464 506465] [     1      8      9 ... 506429 506445 506451]
[     0      1      2 ... 506463 506464 506465] [     3     14     23 ... 506443 506450 506459]
[     0      1      2 ... 506463 506464 506465] [    13     19     25 ... 506392 506402 506421]
[     0      1      2 ... 506463 506464 506465] [     5     15   

In [52]:
#Randomforest classification
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 100, random_state = 1) # Instantiate model with 100 decision trees
rf.fit(X_train, Y_train);#train model on training data

In [53]:
predictions = rf.predict(X_test) #make predictions on test data
errors = abs(predictions - Y_test) #calculate absolute errors
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 2.39 degrees.


In [54]:
#calculating accuracy
mape = 100 * (errors / Y_test) #calculate mean absolute percentage error mape
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 0.0 %.


In [55]:
#Naive Bayes calssification
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
model = GaussianNB()
model.fit(X_train,Y_train)

GaussianNB()

In [56]:
Y_pred = model.predict(X_test)

In [57]:
accuracy = accuracy_score(Y_test,Y_pred)*100
accuracy

59.97196280135052

In [42]:
from sklearn import svm

In [43]:
clf = svm.SVC(kernel='linear')

In [ ]:
clf.fit(X_train,Y_train)

In [ ]:
Y_pred = clf.predict(X_test)

In [ ]:
from sklearn import metrics

In [ ]:
print("accuracy:", metrics.accuracy_score(Y_test,Y_pred))

In [26]:
from sklearn.metrics import confusion_matrix
from sklearn import tree, metrics
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [27]:
dtree = tree.DecisionTreeClassifier(criterion='entropy', max_depth=5,random_state=0)
dtree.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=0)

In [28]:
y_pred = dtree.predict(X_test)

In [29]:
count_misclassified = (Y_test != y_pred).sum()
print('Misclassified samples: {}'.format(count_misclassified))
accuracy = metrics.accuracy_score(Y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))

Misclassified samples: 40546
Accuracy: 0.60


In [8]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import matplotlib as plt
import numpy as np
import random
import warnings

Using TensorFlow backend.


In [10]:
#importing the dataset
data = pd.read_csv(r'C:\Users\krish\anaconda3\csv\bcsc2013.csv')
#data.head()
print(data)
X = data.iloc[:, [0,10]]
Y = data.iloc[:, 11]

        year  race_eth  age_menarche  age_first_birth  current_hrt  menopaus  \
0       2013         1             9                9            0         2   
1       2013         1             9                9            0         2   
2       2013         1             9                9            0         2   
3       2013         1             9                9            0         2   
4       2013         1             9                9            0         2   
...      ...       ...           ...              ...          ...       ...   
506461  2017         9             9                9            9         2   
506462  2017         9             9                9            0         2   
506463  2017         9             9                9            9         2   
506464  2017         9             9                9            0         2   
506465  2017         9             9                9            9         2   

        bmi_group  biophx  count  age  

In [11]:
# define the keras model
model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [12]:
#compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [13]:
# fit the keras model on the dataset
model.fit(X, Y, epochs=150, batch_size=32)

Epoch 1/150
506466/506466 [==============================] - 23s 45us/step - loss: -185701396.9017 - accuracy: 0.1519
Epoch 2/150
506466/506466 [==============================] - 25s 49us/step - loss: -1994438216.0928 - accuracy: 0.1519
Epoch 3/150
506466/506466 [==============================] - 28s 56us/step - loss: -7376128622.1142 - accuracy: 0.1519
Epoch 4/150
506466/506466 [==============================] - 32s 64us/step - loss: -18144437021.1157 - accuracy: 0.1519
Epoch 5/150
506466/506466 [==============================] - ETA: 0s - loss: -36048813336.2029 - accuracy: 0.151 - 30s 59us/step - loss: -36059950872.1986 - accuracy: 0.1519
Epoch 6/150
506466/506466 [==============================] - 26s 52us/step - loss: -63082179325.5465 - accuracy: 0.1519
Epoch 7/150
506466/506466 [==============================] - 22s 43us/step - loss: -100791378557.7087 - accuracy: 0.1519
Epoch 8/150
506466/506466 [==============================] - 29s 58us/step - loss: -151089141891.1536 - accur

In [14]:
# evaluate the keras model
_, accuracy = model.evaluate(X, Y)
print('Accuracy: %.2f' % (accuracy*100))

506466/506466 [==============================] - 7s 13us/step
Accuracy: 15.19
