In [1]:
#importing the libraries
import pandas as pd
import matplotlib as plt
import numpy as np
import random
import warnings

In [2]:
#importing the dataset
data = pd.read_csv(r'C:\Users\krish\anaconda3\bcsc.csv')
#data.head()
print(data)
X = data.iloc[:, [0,10]]
Y = data.iloc[:, 11]

        year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
0       2013         1                0             9                9   
1       2013         1                0             9                9   
2       2013         1                0             9                9   
3       2013         1                0             9                9   
4       2013         1                0             9                9   
...      ...       ...              ...           ...              ...   
506461  2017         9                9             9                9   
506462  2017         9                9             9                9   
506463  2017         9                9             9                9   
506464  2017         9                9             9                9   
506465  2017         9                9             9                9   

        BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
0                           9       

In [3]:
#fin missing values,if any
data.isnull()

year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
0       False     False            False         False            False   
1       False     False            False         False            False   
2       False     False            False         False            False   
3       False     False            False         False            False   
4       False     False            False         False            False   
...       ...       ...              ...           ...              ...   
506461  False     False            False         False            False   
506462  False     False            False         False            False   
506463  False     False            False         False            False   
506464  False     False            False         False            False   
506465  False     False            False         False            False   

        BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
0                       False        False     False      False   False   
1                       False        False     False      False   False   
2                       False        False     False      False   False   
3                       False        False     False      False   False   
4                       False        False     False      False   False   
...                       ...          ...       ...        ...     ...   
506461                  False        False     False      False   False   
506462                  False        False     False      False   False   
506463                  False        False     False      False   False   
506464                  False        False     False      False   False   
506465                  False        False     False      False   False   

        breast_cancer_history    age  
0                       False  False  
1                       False  False  
2                       False  False  
3                       False  False  
4                       False  False  
...                       ...    ...  
506461                  False  False  
506462                  False  False  
506463                  False  False  
506464                  False  False  
506465                  False  False  

[506466 rows x 12 columns]

In [4]:
#Missing Data Percentage List
for col in data.columns:
    pct_missing = np.mean(data[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))

year - 0%
race_eth - 0%
first_degree_hx - 0%
age_menarche - 0%
age_first_birth - 0%
BIRADS_breast_density - 0%
current_hrt - 0%
menopaus - 0%
bmi_group - 0%
biophx - 0%
breast_cancer_history - 0%
age - 0%


In [31]:
#data['count'].describe()

In [6]:
#data_dedupped = data.drop('count', axis=1).drop_duplicates()
print(data.shape)
print(data_dedupped.shape)

(506466, 12)


NameError: name 'data_dedupped' is not defined

In [7]:
#removing duplicate rows
data.drop_duplicates(subset=None , inplace=True)

In [36]:
print(data)

        year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
0       2013         1                0             9                9   
1       2013         1                0             9                9   
2       2013         1                0             9                9   
3       2013         1                0             9                9   
4       2013         1                0             9                9   
...      ...       ...              ...           ...              ...   
506461  2017         9                9             9                9   
506462  2017         9                9             9                9   
506463  2017         9                9             9                9   
506464  2017         9                9             9                9   
506465  2017         9                9             9                9   

        BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
0                           9       

In [8]:
data.head()

year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
0  2013         1                0             9                9   
1  2013         1                0             9                9   
2  2013         1                0             9                9   
3  2013         1                0             9                9   
4  2013         1                0             9                9   

   BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
0                      9            0         2          2       1   
1                      9            0         2          2       1   
2                      9            0         2          3       0   
3                      9            0         2          3       0   
4                      9            0         2          3       1   

   breast_cancer_history  age  
0                      0    7  
1                      1    7  
2                      0    7  
3                      9    7  
4                      0    7

In [44]:
data.tail()

year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
506461  2017         9                9             9                9   
506462  2017         9                9             9                9   
506463  2017         9                9             9                9   
506464  2017         9                9             9                9   
506465  2017         9                9             9                9   

        BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
506461                      1            9         2          9       1   
506462                      2            0         2          9       0   
506463                      2            9         2          9       9   
506464                      3            0         2          9       0   
506465                      3            9         2          9       9   

        breast_cancer_history  count  age  
506461                      0      1   13  
506462                      0      1   13  
506463                      9      1   13  
506464                      0      1   13  
506465                      0      1   13

In [38]:
len(data)


506466

In [39]:
data.columns

Index(['year', 'race_eth', 'first_degree_hx', 'age_menarche',
       'age_first_birth', 'BIRADS_breast_density', 'current_hrt', 'menopaus',
       'bmi_group', 'biophx', 'breast_cancer_history', 'age'],
      dtype='object')

In [40]:
data.dtypes

year                     int64
race_eth                 int64
first_degree_hx          int64
age_menarche             int64
age_first_birth          int64
BIRADS_breast_density    int64
current_hrt              int64
menopaus                 int64
bmi_group                int64
biophx                   int64
breast_cancer_history    int64
age                      int64
dtype: object

In [41]:
data.index

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            506456, 506457, 506458, 506459, 506460, 506461, 506462, 506463,
            506464, 506465],
           dtype='int64', length=506466)

In [42]:
data.age.unique()

array([ 7,  8,  9, 10, 11, 12, 13,  1,  2,  3,  4,  5,  6], dtype=int64)

In [43]:
data.age.value_counts()

7     89019
6     70841
8     62206
9     59652
5     49942
10    48966
11    34689
4     34495
12    22795
13    14557
3     12084
2      5793
1      1427
Name: age, dtype: int64

In [9]:
#binning the age_categories 1 to 13 to 5 different bins "age"
bins = [1, 4, 7, 10, 13]
group_names = ['group1' , 'group2' , 'group3' , 'group4']

In [10]:
age_categories = pd.cut(data['age'], bins, labels=group_names)
age_categories

0         group2
1         group2
2         group2
3         group2
4         group2
           ...  
506461    group4
506462    group4
506463    group4
506464    group4
506465    group4
Name: age, Length: 506466, dtype: category
Categories (4, object): ['group1' < 'group2' < 'group3' < 'group4']

In [11]:
#pre processing the data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
X = scaler.fit_transform(X)

In [12]:
#shuffling the data
data = data.sample(frac=1).reset_index(drop=True)

In [13]:
data.head()

year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
0  2013         1                0             0                9   
1  2014         1                0             0                4   
2  2016         1                0             1                3   
3  2017         1                0             2                4   
4  2014         1                0             1                4   

   BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
0                      1            1         2          4       0   
1                      3            9         2          9       1   
2                      3            0         2          3       0   
3                      2            0         2          9       0   
4                      3            0         1          3       1   

   breast_cancer_history  age  
0                      0    9  
1                      1    8  
2                      0    9  
3                      1   10  
4                      9    5

In [14]:
#Splitting the dataset into the Training set and Test set to 80 and 20
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 123)
print (X_train.shape , Y_train.shape)
print (X_test.shape, Y_test.shape)

(405172, 2) (405172,)
(101294, 2) (101294,)


In [15]:
data.tail()

year  race_eth  first_degree_hx  age_menarche  age_first_birth  \
506461  2016         2                0             9                0   
506462  2017         9                0             9                9   
506463  2014         2                1             0                3   
506464  2015         1                0             9                3   
506465  2013         5                1             1                0   

        BIRADS_breast_density  current_hrt  menopaus  bmi_group  biophx  \
506461                      3            1         2          1       0   
506462                      3            9         2          4       1   
506463                      3            0         1          2       0   
506464                      3            0         3          4       1   
506465                      1            0         2          2       1   

        breast_cancer_history  age  
506461                      9    8  
506462                      0    9  
506463                      0    7  
506464                      0    5  
506465                      0   10

In [16]:
#ignore all caught warnings   
with warnings.catch_warnings():
    warnings.filterwarnings("ignore")

from sklearn.model_selection import KFold
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score
scores = []
best_svr = SVR(kernel='rbf', gamma = 'scale')
cv = KFold(n_splits=10, random_state=42, shuffle=True)
#for train_index, test_index in cv.split(X):
    #print("Train Index: ", train_index, "\n")
    #print("Test Index: ", test_index)
print ("Train Set                                            Test Set         ")
for train_set,test_set in cv.split(X):
    print(train_set , test_set)

    #X_train, X_test, Y_train, Y_test = X[train_index], X[test_index], Y[train_index], Y[test_index]


    


Train Set                                            Test Set         
[     0      1      2 ... 506462 506464 506465] [     6      7     24 ... 506449 506461 506463]
[     0      1      3 ... 506462 506463 506464] [     2     26     39 ... 506442 506448 506465]
[     0      1      2 ... 506463 506464 506465] [    11     28     35 ... 506395 506446 506455]
[     1      2      3 ... 506462 506463 506465] [     0     16     17 ... 506452 506454 506464]
[     0      1      2 ... 506463 506464 506465] [    10     12     20 ... 506420 506433 506457]
[     0      1      2 ... 506463 506464 506465] [     4     29     38 ... 506447 506456 506462]
[     0      2      3 ... 506463 506464 506465] [     1      8      9 ... 506429 506445 506451]
[     0      1      2 ... 506463 506464 506465] [     3     14     23 ... 506443 506450 506459]
[     0      1      2 ... 506463 506464 506465] [    13     19     25 ... 506392 506402 506421]
[     0      1      2 ... 506463 506464 506465] [     5     15   

In [13]:
#from sklearn import svm
#svc = svm.SVC(kernel='linear',C=1).fit(X,Y) 

In [ ]:
#from sklearn import cross_validation
#from sklearn.model_selection import cross_validate
#from sklearn.cross_validation import KFold, cross_val_score
#from sklearn.model_selection import KFold , cross_val_score
#Kfold = KFold(len(data),n_splits=5,shuffle=False)
#print("KfoldCrossVal score using SVM is %s" %cross_val_score(best_svr,X,Y,cv=10).mean())

In [ ]:
#from sklearn import metrics

In [ ]:
#sm = svc.fit(X_train,Y_train)
#Y_pred = sm.predict(X_test)
#print("Accuracy: {}%".format(sm.score(X_test, Y_test) * 100 ))

In [17]:
#Randomforest classification
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 1000, random_state = 42) # Instantiate model with 1000 decision trees
rf.fit(X_train, Y_train);#train model on training data

In [18]:
predictions = rf.predict(X_test) #make predictions on test data
errors = abs(predictions - Y_test) #calculate absolute errors
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 2.04 degrees.


In [19]:
#calculating accuracy
mape = 100 * (errors / Y_test) #calculate mean absolute percentage error mape
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 70.28 %.


In [20]:
#Naive Bayes calssification
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
model = GaussianNB()
model.fit(X_train,Y_train)

GaussianNB()

In [21]:
Y_pred = model.predict(X_test)

In [22]:
accuracy = accuracy_score(Y_test,Y_pred)*100
accuracy

17.51831302939957

In [58]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB().fit(X_train,Y_train)

In [59]:
predicted = model.predict(X_test)
print(np.mean(predicted == Y_test))

0.17912215925918612
